# Generated by Django 6.0.7 on 2026-07-20 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0002_rename_workspaces_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace'),
        ),
    ]
